### ISSUE TITLE
opam config needs qtest dependency?

### ISSUE THREAD

**Issue by waclena** [c-cube/sequence#10]
Not a big deal, but, I tried to install sequence via opam -- I did not have qtest installed -- and it fails:

> #=== ERROR while installing sequence.0.10 =====================================#
> # opam-version 1.2.2
> # os           linux
> # command      make build
> # path         /usr/app/lib/opam/4.03.0/build/sequence.0.10
> # compiler     4.03.0
> # exit-code    2
> # env-file     /usr/app/lib/opam/4.03.0/build/sequence.0.10/sequence-28014-c61e7b.env
> # stdout-file  /usr/app/lib/opam/4.03.0/build/sequence.0.10/sequence-28014-c61e7b.out
> # stderr-file  /usr/app/lib/opam/4.03.0/build/sequence.0.10/sequence-28014-c61e7b.err
> ### stdout ###
> # ocaml setup.ml -build
> # make[1]: Entering directory '/usr/app/lib/opam/4.03.0/build/sequence.0.10'
> # make[1]: Leaving directory '/usr/app/lib/opam/4.03.0/build/sequence.0.10'
> ### stderr ###
> # make[1]: *** [Makefile:55: qtest-gen] Error 2
> # E: Failure("Command 'make qtest-gen' terminated with error code 2")
> # make: *** [Makefile:7: build] Error 1`

After installing qtest, sequence installs with no problem.

Thanks for all the great code btw.

**Comment by c-cube** [comment]
Did you use the opam flag for running tests? I could not reproduce on my machine… and reading the makefile, what should happen with `make qtest-gen` is nothing if you don't have anything named "qtest" in your path.

Thanks for the kind words :-)

**Comment by waclena** [comment]
Simon Cruanes <notifications@github.com> writes:

> Did you use the opam flag for running tests? I could not reproduce on
> my machine… and reading the makefile, what should happen with make
> qtest-gen is nothing if you don't have anything named "qtest" in your
> path.

No, at least, not explicitly... Maybe I have it set implicitly somehow?

I don't have OPAMBUILDTEST set:

    $ env | grep OPAM
    OPAMCOLOR=auto
    OPAMROOT=/usr/app/lib/opam
    $

Maybe there's some other way of defaulting it?

Anyway, must be my bad.  Sorry for the noise!  :-)

**Comment by c-cube** [comment]
Nah, if there's a bug I want to fix it! ^^
Do you have something named `qtest` on your path? Can you, if you have time, clone this repo and try to build it manually?

**Comment by waclena** [comment]
Simon Cruanes <notifications@github.com> writes:

> Nah, if there's a bug I want to fix it! ^^
> Do you have something named `qtest` on your path?

Sure enough!  An ancient, pre-opam version of qtest!

    $ type -a qtest
    qtest is /usr/app/lib/opam/4.03.0/bin/qtest
    qtest is /usr/app/bin/qtest
    $ /usr/app/lib/opam/4.03.0/bin/qtest
    qtest v2.1.1: use --help for usage notes.
    $ /usr/app/bin/qtest
    qtest: use --help for usage notes.

After removing that old qtest and the opam qtest (which I installed for
sequence), sequence now builds perfectly:

    $ rm /usr/app/bin/qtest
    $ opam remove qtest sequence
    The following actions will be performed:
      ⊘  remove qtest    2.5
      ⊘  remove sequence 0.10
    ===== ⊘  2 =====

    =-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    [qtest] Archive in cache

    =-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    ⊘  removed   qtest.2.5
    ⊘  removed   sequence.0.10
    Done.
    $ opam install sequence
    The following actions will be performed:
      ∗  install sequence 0.10

    =-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    [sequence] Archive in cache

    =-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    ∗  installed sequence.0.10
    Done.
    $

Thanks for the help!

**Comment by c-cube** [comment]
Ah, perfect! Glad that it's fixed. Cheers!
