### ISSUE TITLE
should this be included into batteries?

### ISSUE THREAD

**Issue by UnixJunkie** [c-cube/sequence#15]
I would push for it, if needed.

**Comment by c-cube** [comment]
I don't know if the combinators here should be part of batteries. It's possible to define the `'a sequence` type in batteries (as I do in containers) and consume/produce it without using this library. Otoh, having `of_seq/to_seq` combinators is definitely useful (there's and old batteries-3-alpha branch with that somewhere).

You should post that on batteries' issue tracker ;)
