### ISSUE TITLE
4.07 support

### ISSUE THREAD

**Issue by copy** [c-cube/sequence#18]
See: https://github.com/ocaml/opam-repository/pull/12135

**Comment by copy** [comment]
Just needs a release, actually. `opam pin add sequence --dev-repo` is already working.

**Comment by c-cube** [comment]
seems I made a release that never got to opam. That should be fixed when https://github.com/ocaml/opam-repository/pull/12345 is merged.

**Comment by c-cube** [comment]
Can you check once the merge of 1.1 is effective?

**Comment by copy** [comment]
Yeah, all working. Cheers!
