### ISSUE TITLE
  Labels version of the signature(s)

### ISSUE THREAD

**Issue by smondet** [c-cube/sequence#7]
Yes, like https://github.com/c-cube/gen/issues/5 :)

**Comment by smondet** [comment]
Answering to https://twitter.com/das_kube/status/554002484247941120 :)

we can do like `List` and `ListLabels` maybe? 2 signatures 1 structure

**Comment by c-cube** [comment]
Interesting, I never looked at how `ListLabels` was implemented. I'm not sure how the type checker accepts it, still, but I'll consider adding this to sequence and gen.

**Comment by c-cube** [comment]
`GenLabels` will be in the next release (soon!). You can check it in the last commit in master.
